# Generated by Django 5.2 on 2025-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=550, unique=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='twofactordevice',
            name='secret',
            field=models.CharField(max_length=550, verbose_name='secret key'),
        ),
    ]
