# Generated by Django 5.2 on 2025-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0002_alter_refreshtoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="twofactordevice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor_devices",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
    ]
