# Generated by Django 5.2 on 2025-04-19 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('redirect_uri', models.CharField(max_length=2000, verbose_name='redirect URI')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('code_challenge', models.CharField(blank=True, max_length=255, verbose_name='code challenge')),
                ('code_challenge_method', models.CharField(blank=True, max_length=10, verbose_name='code challenge method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='used')),
            ],
            options={
                'verbose_name': 'OAuth2 authorization code',
                'verbose_name_plural': 'OAuth2 authorization codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('client_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='client ID')),
                ('client_secret', models.CharField(editable=False, max_length=255, verbose_name='client secret')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default='confidential', max_length=15, verbose_name='client type')),
                ('allowed_grant_types', models.JSONField(default=list, verbose_name='allowed grant types')),
                ('redirect_uris', models.JSONField(default=list, verbose_name='redirect URIs')),
                ('post_logout_redirect_uris', models.JSONField(default=list, verbose_name='post logout redirect URIs')),
                ('allowed_scopes', models.JSONField(default=list, verbose_name='allowed scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo_url', models.URLField(blank=True, verbose_name='logo URL')),
                ('website_url', models.URLField(blank=True, verbose_name='website URL')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='privacy policy URL')),
                ('terms_of_service_url', models.URLField(blank=True, verbose_name='terms of service URL')),
                ('jwt_algorithm', models.CharField(default='HS256', max_length=10, verbose_name='JWT algorithm')),
                ('access_token_lifetime', models.PositiveIntegerField(default=3600, verbose_name='access token lifetime in seconds')),
                ('refresh_token_lifetime', models.PositiveIntegerField(default=604800, verbose_name='refresh token lifetime in seconds')),
            ],
            options={
                'verbose_name': 'OAuth2 client',
                'verbose_name_plural': 'OAuth2 clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(editable=False, max_length=255, unique=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='refresh token')),
                ('token_type', models.CharField(choices=[('bearer', 'Bearer'), ('mac', 'MAC')], default='bearer', max_length=10, verbose_name='token type')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('access_token_expires_at', models.DateTimeField(verbose_name='access token expires at')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='refresh token expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='client IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'OAuth2 token',
                'verbose_name_plural': 'OAuth2 tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
