# Generated by Django 5.2 on 2025-06-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2authorizationcode",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth2_authorization_codes",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth2_clients",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="oauth2token",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth2_tokens",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
    ]
