# Generated by Django 5.2 on 2025-04-19 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('authorization', 'Authorization'), ('user', 'User Management'), ('role', 'Role Management'), ('permission', 'Permission Management'), ('api_key', 'API Key Management'), ('oauth2', 'OAuth2'), ('admin', 'Administrative'), ('system', 'System')], max_length=20, verbose_name='category')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_success', '2FA Success'), ('2fa_failure', '2FA Failure'), ('access_denied', 'Access Denied'), ('access_granted', 'Access Granted'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('permission_assigned', 'Permission Assigned'), ('permission_removed', 'Permission Removed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('permission_created', 'Permission Created'), ('permission_updated', 'Permission Updated'), ('permission_deleted', 'Permission Deleted'), ('api_key_created', 'API Key Created'), ('api_key_updated', 'API Key Updated'), ('api_key_deleted', 'API Key Deleted'), ('api_key_used', 'API Key Used'), ('oauth2_client_created', 'OAuth2 Client Created'), ('oauth2_client_updated', 'OAuth2 Client Updated'), ('oauth2_client_deleted', 'OAuth2 Client Deleted'), ('oauth2_authorization_granted', 'OAuth2 Authorization Granted'), ('oauth2_token_issued', 'OAuth2 Token Issued'), ('oauth2_token_refreshed', 'OAuth2 Token Refreshed'), ('oauth2_token_revoked', 'OAuth2 Token Revoked'), ('settings_changed', 'Settings Changed'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('system_error', 'System Error'), ('system_warning', 'System Warning'), ('system_info', 'System Information')], max_length=50, verbose_name='event type')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='object ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('hash', models.CharField(blank=True, editable=False, max_length=128, verbose_name='hash')),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=128, verbose_name='previous hash')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
