# Generated by Django 5.2 on 2025-04-19 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True, verbose_name='prefix')),
                ('key', models.CharField(editable=False, max_length=255, verbose_name='key')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('allowed_ips', models.JSONField(blank=True, default=list, verbose_name='allowed IPs')),
                ('allowed_referers', models.JSONField(blank=True, default=list, verbose_name='allowed referers')),
                ('rate_limit_requests', models.PositiveIntegerField(default=0, verbose_name='rate limit requests')),
                ('rate_limit_period', models.PositiveIntegerField(default=0, verbose_name='rate limit period in seconds')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('endpoint', models.CharField(max_length=255, verbose_name='endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='response status')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time (ms)')),
            ],
            options={
                'verbose_name': 'API key usage',
                'verbose_name_plural': 'API key usages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
