# Generated by Django 5.2 on 2025-04-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='apikeyusage',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_keys.apikey', verbose_name='API key'),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('user', 'name')},
        ),
    ]
