# Generated by Django 5.2 on 2025-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(editable=False, max_length=550, verbose_name='key'),
        ),
    ]
