# Generated by Django 5.2 on 2025-04-30 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('protocol', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect'), ('oauth2', 'OAuth 2.0'), ('ldap', 'LDAP/Active Directory')], max_length=10, verbose_name='protocol')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('config', models.JSONField(default=dict, verbose_name='configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'identity provider',
                'verbose_name_plural': 'identity providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSOUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, verbose_name='external ID')),
                ('external_email', models.EmailField(blank=True, max_length=254, verbose_name='external email')),
                ('external_username', models.CharField(blank=True, max_length=255, verbose_name='external username')),
                ('profile_data', models.JSONField(blank=True, default=dict, verbose_name='profile data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identity_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='sso.identityprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO user mapping',
                'verbose_name_plural': 'SSO user mappings',
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='session ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='logged out at')),
                ('user_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sso.ssousermapping')),
            ],
            options={
                'verbose_name': 'SSO session',
                'verbose_name_plural': 'SSO sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ssousermapping',
            index=models.Index(fields=['identity_provider', 'external_id'], name='sso_ssouser_identit_88348d_idx'),
        ),
        migrations.AddIndex(
            model_name='ssousermapping',
            index=models.Index(fields=['identity_provider', 'external_email'], name='sso_ssouser_identit_e99f81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ssousermapping',
            unique_together={('identity_provider', 'external_id')},
        ),
    ]
