# Generated by Django 5.2 on 2025-06-16 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssosession",
            name="user_mapping",
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_providers",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="ssosession",
            name="identity_provider",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sso.identityprovider",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ssosession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_sessions",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AddField(
            model_name="ssosession",
            name="user",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ssousermapping",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_user_mappings",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AlterField(
            model_name="ssousermapping",
            name="identity_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_mappings",
                to="sso.identityprovider",
            ),
        ),
    ]
